# Generated by Django 6.0.3 on 2026-03-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(choices=[('low', 'LOW'), ('medium', 'Medium'), ('high', 'High')]),
        ),
    ]
