# Generated by Django 6.0.3 on 2026-03-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(choices=[('low', 'LOW'), ('medium', 'Medium'), ('high', 'High'), ('mixed', 'Mixed')]),
        ),
    ]
