# Generated by Django 6.0.3 on 2026-03-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Correct Answer'), ('multiple', 'Multiple Correct Answers')], default='single', max_length=10),
        ),
    ]
