# Generated by Django 6.0.3 on 2026-03-09 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal', models.TextField()),
                ('deadline', models.DateField()),
                ('difficulty_level', models.CharField(choices=[('low', 'LOW'), ('medium', 'Medium'), ('high', 'High')], default='low')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='subjects/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text Document')], default='pdf')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('raw_text', models.TextField()),
                ('processed_summary', models.TextField()),
                ('extracted_topics', models.JSONField()),
                ('subject_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_extract', to='subjects.subjectfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
