# Generated by Django 6.0.3 on 2026-03-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='user_id',
            new_name='user',
        ),
    ]
