# Generated by Django 6.0.3 on 2026-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_rename_user_id_subject_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectfile',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='subjectfile',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectfile',
            name='title',
            field=models.CharField(default=2, max_length=1024),
            preserve_default=False,
        ),
    ]
