# Generated by Django 6.0.3 on 2026-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_rename_subject_id_subjectfile_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='subjectextract',
            name='difficulty_level',
            field=models.CharField(choices=[('low', 'LOW'), ('medium', 'Medium'), ('high', 'High')], default='low'),
        ),
    ]
