# Generated by Django 6.0.3 on 2026-03-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_remove_subject_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('difficulty_level', models.CharField(choices=[('low', 'LOW'), ('medium', 'Medium'), ('high', 'High')], default='low')),
                ('summary', models.TextField()),
                ('topics', models.JSONField()),
                ('key_points', models.JSONField()),
                ('recommended_focus', models.JSONField()),
                ('estimated_hours', models.IntegerField()),
                ('Subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_analyze', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SubjectExtract',
        ),
    ]
