# Generated by Django 6.0.3 on 2026-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_subjectanalyze_delete_subjectextract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectanalyze',
            old_name='Subject',
            new_name='subject',
        ),
    ]
