# Generated by Django 6.0.3 on 2026-03-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_rename_subject_subjectanalyze_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectanalyze',
            name='concepts',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectanalyze',
            name='subtopics',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectanalyze',
            name='topic_wise_priority',
            field=models.JSONField(null=True),
        ),
    ]
