# Generated by Django 6.0.3 on 2026-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_subjectanalyze_concepts_subjectanalyze_subtopics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_analyzing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_failed_analyze',
            field=models.BooleanField(default=False),
        ),
    ]
