# Generated by Django 6.0.3 on 2026-03-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0010_subject_is_analyzing_subject_is_failed_analyze'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('daily_study_hours', models.IntegerField(blank=True, null=True)),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_creating', models.BooleanField(default=True)),
                ('is_failed', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('estimated_hours', models.IntegerField()),
                ('starting_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='planning.studyplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_session', to='planning.planitems')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
